[package]
name = "api-server"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true } 
aya = { workspace = true, features = ["async_tokio"] }
common = { workspace = true, features = ["user"] }
libc = { workspace = true } 
log = { workspace = true }
prost = { workspace = true }
regex = { workspace = true } 
tokio = { workspace = true , features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tonic = { workspace = true, features = ["tls"] }
tonic-health = { workspace = true } 

[build-dependencies]
tonic-build = { workspace = true }
