[package]
name = "api-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
prost = "0.11.2"
tonic = "0.8.2"
anyhow = "1"
log = "0.4"
aya = { version = ">=0.11", features=["async_tokio"] }
tokio = { version = "1.18", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
common = { path = "../common", features=["user"] }

[build-dependencies]
tonic-build = "0.8.2"
