apiVersion: bpfd.io/v1alpha1
kind: TcProgram
metadata:
  labels:
    app.kubernetes.io/name: blixt-tc-ingress
  name: blixt-tc-ingress
spec:
  sectionname: tc_ingress
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    primarynodeinterface: true
  priority: 0
  direction: ingress
  bytecode:
    image:
      url: quay.io/bpfd-bytecode/blixt-tc-ingress:latest
      imagepullpolicy: Always