
resources: 
- ../udproute
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: blixt-udproute-sample
  spec:
    template:
      spec:
        containers:
        - name: server
          command:
            - ./udp-test-server
            - --dry-run