apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dataplane
  namespace: system
  labels:
    app: dataplane
spec:
  selector:
    matchLabels:
      app: dataplane
  template:
    metadata:
      labels:
        app: dataplane
    spec:
      serviceAccountName: udproute-manager
      hostNetwork: true
      containers:
      - name: dataplane
        image: ghcr.io/kong/blixt-dataplane:latest
        securityContext:
          privileged: true
        args: ["--iface", "eth0"]
        env:
        - name: RUST_LOG
          value: info
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9874
